DROP TABLE IF EXISTS TRATAMENTO;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS MEDICO;
DROP TABLE IF EXISTS ESPECIALIDADE;
DROP TABLE IF EXISTS QUARTO;

CREATE TABLE ESPECIALIDADE(
 id INTEGER PRIMARY KEY,
 nome VARCHAR(255)
);

CREATE TABLE MEDICO(
 crm INTEGER PRIMARY KEY,
 nome VARCHAR(255),
 vaga INTEGER
);

CREATE TABLE PACIENTE(
 cpf CHAR(11) PRIMARY KEY,
 nome VARCHAR(255),
 d_nasc DATE,
 crm_resp INTEGER,
 FOREIGN KEY (crm_resp) REFERENCES MEDICO(crm)
);

CREATE TABLE TRATAMENTO(
 crm INTEGER,
 cpf CHAR(11),
 PRIMARY KEY(cpf,crm),
 FOREIGN KEY(cpf) REFERENCES PACIENTE(cpf),
 FOREIGN KEY(crm) REFERENCES MEDICO(crm)
);

