DROP TABLE IF EXISTS PECA;
DROP TABLE IF EXISTS REPARO;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS VEIC_CLIEN;
DROP TABLE IF EXISTS VEICULO;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE(
  id INTEGER PRIMARY KEY
);

CREATE TABLE VEICULO(
  placa VARCHAR(6)PRIMARY KEY
);

CREATE TABLE VEIC_CLIEN(
  id_clien INTEGER,
  placa VARCHAR(6),
  PRIMARY KEY(id_clien,placa),
  FOREIGN KEY(id_clien) REFERENCES CLIENTE(id),
  FOREIGN KEY(placa) REFERENCES VEICULO(placa)
);

CREATE TABLE CATEGORIA(
  nome VARCHAR(255),
  custo FLOAT,
  PRIMARY KEY(nome)
);

CREATE TABLE FUNCIONARIO(
  id INTEGER PRIMARY KEY
);

CREATE TABLE REPARO(
  id INTEGER PRIMARY KEY,
  custo FLOAT,
  dat DATE
);

CREATE TABLE PECA(
  cod INTEGER PRIMARY KEY
);

CREATE TABLE REP_PEC(
  id_rep INTEGER,
  cod INTEGER,
  PRIMARY KEY(id_rep,cod),
  FOREIGN KEY(id_rep)REFERENCES
);




