DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS FUNC_ENTREG;
DROP TABLE IF EXISTS FUNC_ATEND;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS BAIRRO;
DROP TABLE IF EXISTS TAMANHO;
DROP TABLE IF EXISTS PIZZA;

CREATE TABLE PIZZA(
  numero INTEGER PRIMARY KEY,
  nome VARCHAR(50),
  ingredientes VARCHAR(255)
);

CREATE TABLE TAMANHO( 
  descricao VARCHAR(50) PRIMARY KEY
);

CREATE TABLE TEM_TAM(
  preco FLOAT,
  num_pizza INTEGER,
  des_tam VARCHAR(50),
  PRIMARY KEY(num_pizza,des_tam),
  FOREIGN KEY(num_pizza)REFERENCES PIZZA(numero),
  FOREIGN KEY(des_tam)REFERENCES TAMANHO(descricao)
);

CREATE TABLE BAIRR0(
  nome VARCHAR(50)PRIMARY KEY,
  tempo TIME,
);

CREATE TABLE CLIENTE(
  telefone VARCHAR(10)PRIMARY KEY,
  nome VARCHAR(50),
  nome_bairro VARCHAR(50),
  FOREIGN KEY(nome_bairro)REFERENCES BAIRRO(nome)
);

CREATE TABLE FUNCIONARIO(
  id INTEGER PRIMARY KEY
);

CREATE TABLE FUNC_ATEND( 
  id INTEGER PRIMARY KEY,
  FOREIGN KEY(id)REFERENCES FUNCIONARIO(id)
);

CREATE TABLE FUNC_ENTREG( 
  id INTEGER PRIMARY KEY,
  tel VARCHAR(10),
  FOREIGN KEY(id)REFERENCES FUNCIONARIO(id)
);



CREATE TABLE PEDIDO(
  num INTEGER PRIMARY KEY,
  dat DATE,
  endereco VARCHAR(255),  
  num_pizza INTEGER,
  des_tam VARCHAR(50),
  id_entreg INTEGER,
  id_atend INTEGER,
  tel_client VARCHAR(10),
  FOREIGN KEY(num_pizza,des_tam) REFERENCES TEM_TAM(num_pizza,des_tam),
  FOREIGN KEY(id_entreg)REFERENCES FUNC_ENTREG(id),
  FOREIGN KEY(id_atend)REFERENCES FUNC_ATEND(id),
  FOREIGN KEY(tel_client)REFERENCES CLIENTE(telefone),
);

